# Generated by Django 3.1.4 on 2021-01-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('appoint', '0002_doctor_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Moderator',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('M', 'Moderator'), ('D', 'Doctor'), ('C', 'Customer')], default='C', max_length=1, verbose_name='Type'),
        ),
    ]
