# Generated by Django 3.1.4 on 2021-01-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0003_auto_20210116_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderator',
            options={'ordering': ['last_name']},
        ),
    ]
