# Generated by Django 3.2 on 2021-04-25 12:46

import appoint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0004_auto_20210117_1705'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', appoint.models.CustomerManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('objects', appoint.models.DoctorManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='moderator',
            managers=[
                ('objects', appoint.models.ModeratorManager()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
