# Generated by Django 3.1.4 on 2021-01-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='info',
            field=models.TextField(blank=True, max_length=1250, verbose_name='Information'),
        ),
    ]
